image: python:3.6-alpine

stages:
  - deploy

before_script:
   - pip install -r requirements_dev.txt
   - python setup.py sdist bdist_wheel

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags
