image: python:3.6-alpine

stages:
  - build
  - test
  - deploy

build_package:
  stage: build
  script:
    - apk add gcc g++ make libffi-dev openssl-dev
    - pip install -r requirements_dev.txt
    - python setup.py sdist bdist_wheel
  only:
    - tags

test_package:
  stage: test
  script:
    - coverage run setup.py test
    - coverage html
  only:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags
