image: python:3.6-alpine

services:
  - eclipse-mosquitto
  - influxdb:1.5.4-alpine

stages:
  - build
  - test
  - deploy

build_package:
  stage: build
  script:
    - apk add gcc g++ make libffi-dev openssl-dev
    - pip install -r requirements_dev.txt
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  only:
    - tags

test_package:
  stage: test
  script:
    - pip install -r requirements_dev.txt
    - tox
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 day
  only:
    - tags

pages:
    stage: deploy
    before_script:
      - "true"
    script:
      - mkdir -p public/coverage
      - cp -fr htmlcov/* public/coverage/
    dependencies:
      - test_package
    artifacts:
      paths:
        - public
    only:
      - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - pip install twine
    - twine upload dist/*
  dependencies:
    - build_package
  only:
    - tags
